### PR TITLE
moved therapist infos to bottom of screen

### PR DESCRIPTION
**Pull request by vinyll**
Note that it breaks the display of description. Not sure how to deal with it

### CODE REVIEW

**Comment by fuentesloic** [comment]
we did that (put therapist on the bottom) but we change for the top because you ask for that.

So why now we reput it at the bottom ?

**Comment by vinyll** [comment]
Did I ask for that? We may have had a misunderstanding then…
We wanted to have the banner with the therapist à-la-Medium: constantly visible in the bottom of the screen.
cf mail from Nathalie on June 4th: _La position du bandeau est haute, nous avions parlé d'une position basse sur la page._

**Comment by fuentesloic** [comment]
I will work on it when #26 will be merged ;)

**Comment by fuentesloic** [comment]
@vinyll what do you think now ?

**Comment by vinyll** [comment]
Funny I cannot approve your commit because I'm the assignee ^^

good for me 👍

**Pull request merged**
