### PR TITLE
Design try from hyperspace

### PR DESCRIPTION
**Pull request by fuentesloic**
capture d ecran 2016-11-14 a 23 43 35
capture d ecran 2016-11-14 a 23 43 42

### CODE REVIEW

**Comment by vinyll** [comment]
I like this better than the previous one, even though it is still too purple and we lost the _Vitruvian Man_.
Also I wonder how accessible the menu in the bottom left would be when a screen in short in height.

**Comment by fuentesloic** [comment]
Ok, but I have a couple of question:
- You want keep the _Vitruvian Man_ ?
- About how is accesible the menu if the screen would be short in height, maybe we could hidden the _poor_ information like this picture
capture d ecran 2016-11-15 a 15 21 00

**Comment by vinyll** [comment]
The theme is Da Vinci; so yes, we should keep _Vitruvian Man_ ;)
Maybe we should shrink the menu a little.
I guess the idea of removing the picture when the screen is too small may be a good idea 👍

**Comment by fuentesloic** [comment]
@vinyll : ok you can make a review again

**Pull request closed without merging**
